export const data = [
    {
        id: "1",
        jobTitle: "UX UI Designer",
        companyName: "Great Vibes",
        industry: "Information Technology",
        location: "Chennai, Tamil Nadu, India (In-office)",
        remoteType: "Part-Time (9.00 am - 5.00 pm IST)",
        minExperience: "1",
        maxExperience: "2",
        minSalary: "30000",
        maxSalary: "50000",
        totalEmployees: "51-100",
        applyType: "both",
        "{}": "",
    },
    {
        id: "2",
        jobTitle: "Developer",
        companyName: "Great Vibes",
        industry: "Information Technology",
        location: "Chennai, Tamil Nadu, India (In-office)",
        remoteType: "Part-Time (9.00 am - 5.00 pm IST)",
        minExperience: "1",
        maxExperience: "2",
        minSalary: "30000",
        maxSalary: "50000",
        totalEmployees: "51-100",
        applyType: "both",
    },
    {
        id: "3",
        jobTitle: "Interaction Designer",
        companyName: "Great Vibes",
        industry: "Information Technology",
        location: "Chennai, Tamil Nadu, India (In-office)",
        remoteType: "Part-Time (9.00 am - 5.00 pm IST)",
        minExperience: "1",
        maxExperience: "2",
        minSalary: "30000",
        maxSalary: "50000",
        totalEmployees: "51-100",
        applyType: "both",
    },
    {
        id: "4",
        jobTitle: "SEO Analyst",
        companyName: "Great Vibes",
        industry: "Information Technology",
        location: "Chennai, Tamil Nadu, India (In-office)",
        remoteType: "Part-Time (9.00 am - 5.00 pm IST)",
        minExperience: "1",
        maxExperience: "2",
        minSalary: "30000",
        maxSalary: "50000",
        totalEmployees: "51-100",
        applyType: "both",
    },
];
